// One-shot generator: Natural Earth 110m countries (public domain, via
// world-atlas) -> flat SVG path strings keyed by ISO alpha-2, projected with
// geoNaturalEarth1 to match the flat editorial look of the US Albers map.
// Run: bun scripts/gen-world-map.ts   (writes src/data/worldCountryPaths.ts)
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import countriesTopo from "world-atlas/countries-110m.json";
import iso from "i18n-iso-countries";

const W = 959;
const H = 500;

const topo = countriesTopo as any;
const fc = feature(topo, topo.objects.countries) as any;

// Antarctica off BEFORE fitting: it's dead weight on an activism map and its
// latitude span would shrink every real country in the projection fit.
fc.features = fc.features.filter(
  (f: any) => iso.numericToAlpha2(String(f.id).padStart(3, "0")) !== "AQ",
);

const projection = geoNaturalEarth1().fitSize([W, H], fc);
const path = geoPath(projection);

const paths: Record<string, string> = {};
const names: Record<string, string> = {};
let skipped: string[] = [];

for (const f of fc.features) {
  const numeric = String(f.id).padStart(3, "0");
  const alpha2 = iso.numericToAlpha2(numeric);
  if (!alpha2) {
    skipped.push(`${numeric} ${f.properties?.name}`);
    continue;
  }
  const d = path(f);
  if (!d) continue;
  // round coords to 1 decimal to keep the bundle lean
  paths[alpha2] = d.replace(/(\d+\.\d{2,})/g, (m) => Number.parseFloat(m).toFixed(1));
  names[alpha2] = iso.getName(alpha2, "en") ?? f.properties?.name ?? alpha2;
}

// Crop the viewBox to what's actually drawn so the map fills its box edge to
// edge — no dead margins around the projection.
const [[bx0, by0], [bx1, by1]] = path.bounds(fc);
const PAD = 4;
const vb = `${(bx0 - PAD).toFixed(1)} ${(by0 - PAD).toFixed(1)} ${(bx1 - bx0 + PAD * 2).toFixed(1)} ${(by1 - by0 + PAD * 2).toFixed(1)}`;

const sorted = Object.keys(paths).sort();
const out = `// GENERATED by scripts/gen-world-map.ts — do not hand-edit.
// Source: Natural Earth 110m via world-atlas (public domain), geoNaturalEarth1.
export const WORLD_VIEWBOX = "${vb}";
export const WORLD_PATHS: Record<string, string> = {
${sorted.map((k) => `  ${k}: ${JSON.stringify(paths[k])},`).join("\n")}
};
export const WORLD_NAMES: Record<string, string> = ${JSON.stringify(
  Object.fromEntries(sorted.map((k) => [k, names[k]])),
  null,
  2,
)};
`;

await Bun.write("src/data/worldCountryPaths.ts", out);

// Country picker list: every ISO alpha-2 with an English name (fuller than the
// 110m map set — small territories can sign even if the map can't shade them).
// US excluded: US signers go through the state flow.
const allAlpha2 = Object.keys(iso.getAlpha2Codes())
  .filter((c) => c !== "US" && c !== "AQ")
  .map((c) => [c, iso.getName(c, "en") ?? c] as const)
  .sort((a, b) => a[1].localeCompare(b[1]));
const countriesOut = `// GENERATED by scripts/gen-world-map.ts — do not hand-edit.
// ISO 3166-1 alpha-2 -> English name. US excluded (US signers pick a state).
export const COUNTRY_OPTIONS: ReadonlyArray<readonly [string, string]> = [
${allAlpha2.map(([c, n]) => `  [${JSON.stringify(c)}, ${JSON.stringify(n)}],`).join("\n")}
];
export const COUNTRY_CODES: ReadonlySet<string> = new Set(COUNTRY_OPTIONS.map(([c]) => c));
`;
await Bun.write("src/data/countries.ts", countriesOut);
console.log(
  `wrote ${sorted.length} map countries + ${allAlpha2.length} picker countries; skipped: ${skipped.join(", ") || "none"}`,
);
